package org.openxdb.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * OpenXDB {@link Statement}: sends one line-protocol command per execution and
 * exposes the parsed result either as a {@link ResultSet} (SELECT/SHOW/EXPLAIN
 * tables) or as an update count (DDL/DML "(N rows affected)" replies).
 */
public class OpenXDBStatement implements Statement {

    protected final OpenXDBConnection connection;
    private boolean closed = false;
    private boolean closeOnCompletion = false;
    private ResultSet currentResult;
    private int currentUpdateCount = -1;
    private int fetchSize = 0;
    private int maxRows = 0;
    private int queryTimeout = 0;
    private SQLWarning warnings;

    public OpenXDBStatement(OpenXDBConnection connection) {
        this.connection = connection;
    }

    // ---- execution ---------------------------------------------------------

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        OpenXDBProtocol.Result res = run(sql);
        if (res.kind != OpenXDBProtocol.Result.Kind.TABLE) {
            throw new SQLException("executeQuery requires a result set, got update reply: " + sql);
        }
        currentResult = new OpenXDBResultSet(this, res);
        currentUpdateCount = -1;
        return currentResult;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        OpenXDBProtocol.Result res = run(sql);
        if (res.kind != OpenXDBProtocol.Result.Kind.AFFECTED) {
            throw new SQLException("executeUpdate requires an update statement, got a result set: " + sql);
        }
        clearResult();
        currentUpdateCount = res.rowCount;
        return currentUpdateCount;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        OpenXDBProtocol.Result res = run(sql);
        clearResult();
        if (res.kind == OpenXDBProtocol.Result.Kind.TABLE) {
            currentResult = new OpenXDBResultSet(this, res);
            return true;
        }
        currentUpdateCount = res.rowCount;
        return false;
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return execute(sql);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return execute(sql);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return execute(sql);
    }

    private OpenXDBProtocol.Result run(String sql) throws SQLException {
        checkOpen();
        connection.ensureTxnStarted();
        try {
            return connection.protocol().command(sql);
        } catch (SQLException e) {
            clearResult();
            throw e;
        }
    }

    // ---- result navigation ---------------------------------------------------

    @Override
    public ResultSet getResultSet() throws SQLException {
        checkOpen();
        return currentResult;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        checkOpen();
        return currentUpdateCount;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return getMoreResults(CLOSE_ALL_RESULTS);
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        checkOpen();
        if (currentResult != null) {
            currentResult.close();
        }
        clearResult();
        return false;
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        throw new SQLFeatureNotSupportedException("generated keys are not supported");
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        return currentUpdateCount;
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return executeUpdate(sql);
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        return executeUpdate(sql);
    }

    // ---- batch (server protocol has no batching; emulate per-statement) ---------

    @Override
    public void addBatch(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("batching is not supported");
    }

    @Override
    public void clearBatch() throws SQLException {
        throw new SQLFeatureNotSupportedException("batching is not supported");
    }

    @Override
    public int[] executeBatch() throws SQLException {
        throw new SQLFeatureNotSupportedException("batching is not supported");
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        throw new SQLFeatureNotSupportedException("batching is not supported");
    }

    // ---- lifecycle -------------------------------------------------------------

    @Override
    public void close() throws SQLException {
        if (closed) {
            return;
        }
        closed = true;
        clearResult();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return closed;
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        closeOnCompletion = true;
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return closeOnCompletion;
    }

    // ---- hints / settings ---------------------------------------------------------

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        checkOpen();
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        return 0;
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        checkOpen();
        if (max < 0) {
            throw new SQLException("max rows must be >= 0");
        }
        maxRows = max;
    }

    @Override
    public int getMaxRows() throws SQLException {
        return maxRows;
    }

    @Override
    public void setLargeMaxRows(long max) throws SQLException {
        setMaxRows((int) max);
    }

    @Override
    public long getLargeMaxRows() throws SQLException {
        return maxRows;
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        checkOpen();
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        checkOpen();
        if (seconds < 0) {
            throw new SQLException("query timeout must be >= 0");
        }
        queryTimeout = seconds;
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        return queryTimeout;
    }

    @Override
    public void cancel() throws SQLException {
        throw new SQLFeatureNotSupportedException("statement cancel is not supported");
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        throw new SQLFeatureNotSupportedException("named cursors are not supported");
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        checkOpen();
        if (direction != ResultSet.FETCH_FORWARD) {
            throw new SQLException("only FETCH_FORWARD is supported");
        }
    }

    @Override
    public int getFetchDirection() throws SQLException {
        return ResultSet.FETCH_FORWARD;
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        checkOpen();
        if (rows < 0) {
            throw new SQLException("fetch size must be >= 0");
        }
        fetchSize = rows;
    }

    @Override
    public int getFetchSize() throws SQLException {
        return fetchSize;
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return ResultSet.CONCUR_READ_ONLY;
    }

    @Override
    public int getResultSetType() throws SQLException {
        return ResultSet.TYPE_FORWARD_ONLY;
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        return ResultSet.CLOSE_CURSORS_AT_COMMIT;
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        checkOpen();
    }

    @Override
    public boolean isPoolable() throws SQLException {
        return false;
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return warnings;
    }

    @Override
    public void clearWarnings() throws SQLException {
        warnings = null;
    }

    @Override
    public Connection getConnection() throws SQLException {
        return connection;
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this);
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        throw new SQLException("cannot unwrap to " + iface.getName());
    }

    protected void checkOpen() throws SQLException {
        if (closed) {
            throw new SQLException("statement is closed");
        }
        connection.checkOpen();
    }

    private void clearResult() {
        currentResult = null;
        currentUpdateCount = -1;
    }

    /** Called by {@link OpenXDBResultSet#close()} to release the statement. */
    void resultClosed(OpenXDBResultSet rs) {
        if (currentResult == rs) {
            currentResult = null;
        }
        if (closeOnCompletion && currentResult == null && currentUpdateCount < 0) {
            try {
                close();
            } catch (SQLException ignore) {
                // best effort
            }
        }
    }
}
