package org.openxdb.jdbc;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * OpenXDB {@link Connection} over the pkg/server line protocol.
 *
 * <p>Transaction model: with {@code autoCommit=true} (default) every statement is
 * committed implicitly by the server. When {@code setAutoCommit(false)} is used a
 * session transaction is started lazily (BEGIN is sent before the first statement
 * of the transaction) and {@link #commit()} / {@link #rollback()} send
 * COMMIT / ROLLBACK. The server protocol has no authentication, so user/password
 * connection properties are ignored.</p>
 */
public class OpenXDBConnection implements Connection {

    private final String host;
    private final int port;
    private final OpenXDBProtocol protocol;
    private boolean autoCommit = true;
    private boolean inTxn = false;
    private boolean closed = false;
    private SQLWarning warnings;

    OpenXDBConnection(String host, int port) throws SQLException {
        this.host = host;
        this.port = port;
        this.protocol = new OpenXDBProtocol(host, port);
    }

    OpenXDBProtocol protocol() {
        return protocol;
    }

    // ---- statements ------------------------------------------------------

    @Override
    public Statement createStatement() throws SQLException {
        return createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        checkOpen();
        return new OpenXDBStatement(this);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
            throws SQLException {
        return createStatement(resultSetType, resultSetConcurrency);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        checkOpen();
        return new OpenXDBPreparedStatement(this, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
            throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
            int resultSetHoldability) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("stored procedures are not supported");
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
            throws SQLException {
        throw new SQLFeatureNotSupportedException("stored procedures are not supported");
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
            int resultSetHoldability) throws SQLException {
        throw new SQLFeatureNotSupportedException("stored procedures are not supported");
    }

    @Override
    public String nativeSQL(String sql) throws SQLException {
        return sql;
    }

    // ---- transactions -----------------------------------------------------

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        checkOpen();
        this.autoCommit = autoCommit;
        if (autoCommit && inTxn) {
            protocol.command("COMMIT");
            inTxn = false;
        }
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
        return autoCommit;
    }

    @Override
    public void commit() throws SQLException {
        checkOpen();
        if (autoCommit) {
            throw new SQLException("commit() not allowed when autoCommit is true");
        }
        if (!inTxn) {
            throw new SQLException("no active transaction to commit");
        }
        protocol.command("COMMIT");
        inTxn = false;
    }

    @Override
    public void rollback() throws SQLException {
        checkOpen();
        if (autoCommit) {
            throw new SQLException("rollback() not allowed when autoCommit is true");
        }
        if (!inTxn) {
            throw new SQLException("no active transaction to roll back");
        }
        protocol.command("ROLLBACK");
        inTxn = false;
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        throw new SQLFeatureNotSupportedException("savepoints are not supported");
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        checkOpen();
        if (level != TRANSACTION_READ_COMMITTED && level != TRANSACTION_READ_UNCOMMITTED) {
            throw new SQLException("unsupported transaction isolation level: " + level);
        }
        // the server provides snapshot isolation for transactions; nothing to set
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        return TRANSACTION_READ_COMMITTED;
    }

    /** Start the SQL session transaction if autoCommit=false and none is active. */
    void ensureTxnStarted() throws SQLException {
        if (!autoCommit && !inTxn) {
            protocol.command("BEGIN");
            inTxn = true;
        }
    }

    // ---- lifecycle ---------------------------------------------------------

    @Override
    public void close() throws SQLException {
        if (closed) {
            return;
        }
        closed = true;
        try {
            if (inTxn) {
                protocol.command("ROLLBACK");
            }
            protocol.command("QUIT");
        } finally {
            protocol.close();
        }
    }

    @Override
    public boolean isClosed() throws SQLException {
        return closed;
    }

    @Override
    public boolean isValid(int timeout) throws SQLException {
        if (closed) {
            return false;
        }
        try {
            protocol.command("PING");
            return true;
        } catch (SQLException e) {
            return false;
        }
    }

    // ---- metadata ------------------------------------------------------------

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        throw new SQLFeatureNotSupportedException("DatabaseMetaData is not supported");
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        checkOpen();
        // the server has no session read-only flag; accepted and ignored
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        return false;
    }

    @Override
    public void setCatalog(String catalog) throws SQLException {
        checkOpen();
        if (catalog != null && !catalog.isEmpty()) {
            throw new SQLFeatureNotSupportedException("catalog selection is not supported");
        }
    }

    @Override
    public String getCatalog() throws SQLException {
        return null;
    }

    @Override
    public void setSchema(String schema) throws SQLException {
        checkOpen();
        if (schema != null && !schema.isEmpty()) {
            throw new SQLFeatureNotSupportedException("schema selection is not supported");
        }
    }

    @Override
    public String getSchema() throws SQLException {
        return null;
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return warnings;
    }

    @Override
    public void clearWarnings() throws SQLException {
        warnings = null;
    }

    @Override
    public Map<String, Class<?>> getTypeMap() throws SQLException {
        throw new SQLFeatureNotSupportedException("type maps are not supported");
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
        throw new SQLFeatureNotSupportedException("type maps are not supported");
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {
        checkOpen();
        if (holdability != ResultSet.CLOSE_CURSORS_AT_COMMIT) {
            throw new SQLException("unsupported holdability: " + holdability);
        }
    }

    @Override
    public int getHoldability() throws SQLException {
        return ResultSet.CLOSE_CURSORS_AT_COMMIT;
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        throw new SQLFeatureNotSupportedException("savepoints are not supported");
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        throw new SQLFeatureNotSupportedException("savepoints are not supported");
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        throw new SQLFeatureNotSupportedException("savepoints are not supported");
    }

    @Override
    public Clob createClob() throws SQLException {
        throw new SQLFeatureNotSupportedException("Clob is not supported");
    }

    @Override
    public Blob createBlob() throws SQLException {
        throw new SQLFeatureNotSupportedException("Blob is not supported");
    }

    @Override
    public NClob createNClob() throws SQLException {
        throw new SQLFeatureNotSupportedException("NClob is not supported");
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        throw new SQLFeatureNotSupportedException("SQLXML is not supported");
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        throw new SQLFeatureNotSupportedException("arrays are not supported");
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        throw new SQLFeatureNotSupportedException("structs are not supported");
    }

    @Override
    public void setClientInfo(String name, String value) throws SQLClientInfoException {
        throw new SQLClientInfoException("client info is not supported", null);
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
        throw new SQLClientInfoException("client info is not supported", null);
    }

    @Override
    public String getClientInfo(String name) throws SQLException {
        return null;
    }

    @Override
    public Properties getClientInfo() throws SQLException {
        return new Properties();
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this);
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) {
            return iface.cast(this);
        }
        throw new SQLException("cannot unwrap to " + iface.getName());
    }

    @Override
    public void abort(Executor executor) throws SQLException {
        closed = true;
        protocol.close();
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
        throw new SQLFeatureNotSupportedException("network timeout is not supported");
    }

    @Override
    public int getNetworkTimeout() throws SQLException {
        return 0;
    }

    void checkOpen() throws SQLException {
        if (closed) {
            throw new SQLException("connection is closed");
        }
    }

    @Override
    public String toString() {
        return "OpenXDBConnection{jdbc:openxdb://" + host + ":" + port + ", closed=" + closed + "}";
    }
}
